
CREATE TABLE SHIPWRECK (
    ID BIGINT SERIAL  PRIMARY KEY,
    CONDITION VARCHAR(255),
    DEPTH INTEGER,
    DESCRIPTION VARCHAR(255),
    LATITUDE double,
    LONGITUDE double,
    NAME VARCHAR(255),
    YEAR_DISCOVERED INTEGER
);

