CREATE SEQUENCE SHIPWRECK_SEQ START WITH 100 INCREMENT BY 1;

CREATE TABLE SHIPWRECK(
    ID INTEGER NULL PRIMARY KEY,
    CONDITION VARCHAR(255),
    DEPTH INTEGER,
    DESCRIPTION VARCHAR(255),
    LATITUDE NUMERIC(9,5),
    LONGITUDE NUMERIC(9,5),
    NAME VARCHAR(255),
    YEAR_DISCOVERED INTEGER
);          

